language: node_js

node_js:
  - node

branches:
  only:
   master

before_script:
  - npm install -g @angular/cli
  - npm install agm-direction

script:
  - ng build --prod

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: uatransport
  region: eu-central-1
  local_dir: dist/client
  skip_cleanup: true


